title: rogeryeh/grandoak432
description: 
theme: just-the-docs
url: https://rogeryeh.art/432grandoak

search_enabled: true
search:
  heading_level: 3
  button: true

logo: "/assets/images/log.png"

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
